# constants.py
TEXT_CONFIDENCE_THRESHOLD = 0
ALPHA_THRESHOLD = 10
SCALING_FACTOR = 0.6
FRAME_SKIP = 1
LOGO_TEMPLATE = None
MANUAL_LOGO_RECTS = []
INPAINT_RADIUS = 30
TEMPLATE_MATCHING_THRESHOLD = 0.75